#+title: lein-droid 0.3.0-beta1 released
#+tags: lein-droid
#+post-type: news
#+nocut: true
#+OPTIONS: toc:nil author:nil

This long due release of lein-droid marks a milestone in making it less magical
and more obvious about what it is doing. Version =0.3.0-beta1= contains some
breaking changes for the projects generated by the older version, so you'd want
to read the notes below to bring your projects up to date. New projects created
with this version will contain all the changes, otherwise to modify the existing
project you can refer to [[https://github.com/clojure-android/lein-droid/blob/master/sample/project.clj][sample project.clj]] (and the whole [[https://github.com/clojure-android/lein-droid/tree/master/sample][sample]]).

Special thanks to [[https://github.com/AdamClements][Adam Clements]] for implementing most of these changes.

- lein-droid doesn't merge/unmerge any profiles by default anymore, and doesn't
  change the =project.clj= map. Instead, users are encouraged to harness
  Leiningen's profile inheritance mechanism. The proposed profile hierarchy
  looks like this:

  : :android-common <--- :release
  :                   \- :dev     <- :default
  :   :android-user <-/

  See more details on the [[https://github.com/clojure-android/lein-droid/wiki/Profiles#android-common][wiki]].

- =AndroidManifest.xml= was replaced by =AndroidManifest.template.xml=. It is
  now a Mustache template which lein-droid passes options to. This enables
  changing the application name when built with different profiles and
  automatically generating =versionName= and =versionCode= from the project
  version in =profiles.clj=. It also solves the problem of rewriting manifest to
  include Internet permission (like lein-droid once did) which was pretty
  unreliable operation. Now the template tackles it too.

- =release= subtask is now deprecated. To create a release version of your
  application use:

  : lein with-profile release droid doall
- Different profiles use different target directories. This is configured inside
  the profiles, so you won't have that until you update your =project.clj=. This
  change allows to have multiple versions built at the same time, and makes no
  longer necessary to clean the =target/= folder each time you build a different
  version.
